// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/driedxml/parser/internal (interfaces: ParserDelegate)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	api "github.com/driedxml/parser/api"
	internal "github.com/driedxml/parser/internal"
	gomock "github.com/golang/mock/gomock"
)

// MockParserDelegate is a mock of ParserDelegate interface.
type MockParserDelegate struct {
	ctrl     *gomock.Controller
	recorder *MockParserDelegateMockRecorder
}

// MockParserDelegateMockRecorder is the mock recorder for MockParserDelegate.
type MockParserDelegateMockRecorder struct {
	mock *MockParserDelegate
}

// NewMockParserDelegate creates a new mock instance.
func NewMockParserDelegate(ctrl *gomock.Controller) *MockParserDelegate {
	mock := &MockParserDelegate{ctrl: ctrl}
	mock.recorder = &MockParserDelegateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParserDelegate) EXPECT() *MockParserDelegateMockRecorder {
	return m.recorder
}

// ReadDocument mocks base method.
func (m *MockParserDelegate) ReadDocument(arg0 *internal.Parser, arg1 context.Context, arg2 chan<- api.Token, arg3 chan<- error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReadDocument", arg0, arg1, arg2, arg3)
}

// ReadDocument indicates an expected call of ReadDocument.
func (mr *MockParserDelegateMockRecorder) ReadDocument(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDocument", reflect.TypeOf((*MockParserDelegate)(nil).ReadDocument), arg0, arg1, arg2, arg3)
}

// ReadProlog mocks base method.
func (m *MockParserDelegate) ReadProlog(arg0 *internal.Parser, arg1 context.Context, arg2 chan<- api.Token, arg3 chan<- error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReadProlog", arg0, arg1, arg2, arg3)
}

// ReadProlog indicates an expected call of ReadProlog.
func (mr *MockParserDelegateMockRecorder) ReadProlog(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadProlog", reflect.TypeOf((*MockParserDelegate)(nil).ReadProlog), arg0, arg1, arg2, arg3)
}
